// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbiWdUeVzoROJg6GngOMKHMV5jmdIPYA',
    appId: '1:238619021125:web:81075196c2d8619e4cb82c',
    messagingSenderId: '238619021125',
    projectId: 'em-attendance-system',
    authDomain: 'em-attendance-system.firebaseapp.com',
    storageBucket: 'em-attendance-system.firebasestorage.app',
    measurementId: 'G-V895M6C746',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcYt7MXadH2aobFjWerQyuCMuplp6XynU',
    appId: '1:238619021125:android:664952e11add520a4cb82c',
    messagingSenderId: '238619021125',
    projectId: 'em-attendance-system',
    storageBucket: 'em-attendance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX491nWbTci2v4ZcSRbbhZapD3FztuHhY',
    appId: '1:238619021125:ios:bd033e9d8f9b2b344cb82c',
    messagingSenderId: '238619021125',
    projectId: 'em-attendance-system',
    storageBucket: 'em-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.emProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX491nWbTci2v4ZcSRbbhZapD3FztuHhY',
    appId: '1:238619021125:ios:bd033e9d8f9b2b344cb82c',
    messagingSenderId: '238619021125',
    projectId: 'em-attendance-system',
    storageBucket: 'em-attendance-system.firebasestorage.app',
    iosBundleId: 'com.example.emProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDbiWdUeVzoROJg6GngOMKHMV5jmdIPYA',
    appId: '1:238619021125:web:98814295e523df034cb82c',
    messagingSenderId: '238619021125',
    projectId: 'em-attendance-system',
    authDomain: 'em-attendance-system.firebaseapp.com',
    storageBucket: 'em-attendance-system.firebasestorage.app',
    measurementId: 'G-ZPWSDQSNYM',
  );

}